spring:

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown.enabled: true

  metrics:
    distribution:
      percentiles-histogram.http.server.requests: true
      sla.http.server.requests: 1ms,5ms

thymeleaf.cache: false