spring:

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
#
# Shutdown endpoint doesn't work - sorry
# as per https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html
#
    shutdown.enabled: true

  metrics:
    distribution:
      percentiles-histogram.http.server.requests: true
      sla.http.server.requests: 1ms,5ms

thymeleaf.cache: false