spring:
  application:
    name: try-spring-boot-getting-started
  profiles:
    active:
#
# Enable "danger" profile by default
#
      - danger

management:
  endpoints:
    web:
      exposure:
#
# See http://localhost:8080/actuator/ for all actuators
#
        include: "*"

  metrics:
    distribution:
      percentiles-histogram.http.server.requests: true
      sla.http.server.requests: 1ms,5ms,50ms,500ms,5s

thymeleaf.cache: false

---
#
# Properties when profile "danger" is enabled
#
spring:
  profiles: danger

management:
  endpoint:
#
# Application can be shut down by HTTP signal
#
    shutdown.enabled: true